Repository Gamify-IT/lecturer-interface, pull requests merged in 2022-09, with the labels that each got.

#27 Add import and export of minigame configurations
  package-lock.json
  package.json
  src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue
  src/components/EditMinigameModals/EditCrosswordpuzzleModal.vue
  src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue
  src/components/ImportExportConfiguration.vue
  src/ts/import-configuration.ts
Labels: feature

#30 Export configuration files as json file
  docker-compose-dev.yaml
  docker-compose.yaml
  src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue
  src/components/EditMinigameModals/EditCrosswordpuzzleModal.vue
  src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue
Labels: maintenance

#31 Add some useful hints to show the user what he can do on the views
  src/components/Sidebar/CourseSidebarMenu.vue
  src/views/CourseView.vue
  src/views/CoursesView.vue
  src/views/MinigameTasksView.vue
  src/views/NPCsView.vue
  src/views/WorldView.vue
Labels: feature

#34 Handle time error on chickenshock configuration
  .nginx/compose/nginx-dev.conf
  docker-compose-dev.yaml
  docker-compose.yaml
  src/components/EditMinigameModals/EditChickenshockConfigurationModal.vue
  src/components/EditMinigameModals/EditFinitequizConfigurationModal.vue
  tests/unit/AreaBox.spec.ts
Labels: maintenance

#33 Add unit test for changing active switch
  tests/unit/AreaBox.spec.ts
Labels: maintenance

#38 fix books map filename
  src/components/MapImageModal.vue
Labels: bug

#39 Remove v-if condition on showing map image modal
  src/components/MapImageModal.vue
Labels: bug
