Repository Gamify-IT/lecturer-interface, pull requests merged in 2022-08, with the labels that each got.

#9 Implement REST API and multiple courses
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/App.vue
  src/__mocks__/axios.ts
  src/components/AreaBox.vue
  src/components/CourseSidebarMenu.vue
  src/components/EditChickenshockConfigurationModal.vue
  src/components/EditMinigameConfigurationModal.vue
  src/components/EditNPCModal.vue
  src/config.ts
  src/main.ts
  src/router/index.ts
  src/store/index.ts
  src/ts/area-rest-client.ts
  src/ts/chickenshock-rest-client.ts
  src/ts/course-rest-client.ts
  src/ts/dungeon-rest-client.ts
  src/ts/minigame-rest-client.ts
  src/ts/models.ts
  src/ts/npc-rest-client.ts
  src/ts/world-rest-client.ts
  src/views/CourseView.vue
  src/views/CoursesView.vue
  src/views/MinigameTasksView.vue
  src/views/NPCsView.vue
  src/views/WorldView.vue
  tests/unit/AreaBox.spec.ts
  tests/unit/CourseView.spec.ts
  tests/unit/CoursesView.spec.ts
  tests/unit/EditChickenshockConfigurationModal.spec.ts
  tests/unit/EditMinigameConfigurationModal.spec.ts
  tests/unit/MinigameTasksView.spec.ts
  tests/unit/NPCsView.spec.ts
  tests/unit/WorldView.spec.ts
  tsconfig.json
Labels: feature

#12 Fix code smells, fix little bugs
  src/components/EditChickenshockConfigurationModal.vue
  src/components/EditNPCModal.vue
  src/ts/course-rest-client.ts
  src/ts/models.ts
  src/views/CourseView.vue
  src/views/MinigameTasksView.vue
  tests/unit/CourseView.spec.ts
  tests/unit/EditChickenshockConfigurationModal.spec.ts
  tests/unit/MinigameTasksView.spec.ts
  tests/unit/NPCsView.spec.ts
  tests/unit/WorldView.spec.ts
Labels: bug, maintenance

#13 Unify edit behavior by creating a component for string attributes
  src/components/AreaBox.vue
  src/components/EditableStringAttribute.vue
  src/views/CourseView.vue
  src/views/WorldView.vue
  tests/unit/CourseView.spec.ts
Labels: bug

#15 Implement course deletion
  src/ts/course-rest-client.ts
  src/views/CourseView.vue
  src/views/CoursesView.vue
Labels: feature

#18 Add image spots
  src/components/MapImageModal.vue
  src/config.ts
  src/ts/models.ts
  src/views/MinigameTasksView.vue
  src/views/NPCsView.vue
  src/views/WorldView.vue
Labels: feature

#17 Add crosswordpuzzle configuration
  src/components/EditCrosswordpuzzleModal.vue
  src/config.ts
  src/ts/crosswordpuzzle-rest-client.ts
  src/ts/models.ts
  src/views/MinigameTasksView.vue
Labels: feature

#23 Add finitequiz configuration
  .nginx/compose/nginx-dev.conf
  .nginx/compose/nginx.conf
  docker-compose-dev.yaml
  docker-compose.yaml
  src/components/EditFinitequizConfigurationModal.vue
  src/config.ts
  src/ts/finitequiz-rest-client.ts
  src/ts/models.ts
  src/views/MinigameTasksView.vue
Labels: feature
